### ISSUE TITLE
Regex fails if workItemId's length < 5

### ISSUE THREAD

**Issue by JoshWhite** [Superformula/azure-test-binder#40]
### Describe the bug

I have a new instance of Azure DevOps, where `workItemId`s start from 1.
As such, the following Regex doesn't pick up my work items:
```
const defaultWorkItemIdPattern = /(#?\d{5})/g
```

### Steps to reproduce

Add task to pipeline for project which has workitems < 5 digits long

**Comment by jamesdunnam-sf** [comment]
Hey Josh, thanks for the contribution. Sorry, this fell by the wayside for a bit.
